# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kro_prod <- function(A, B) {
    .Call(`_tnsrcomp_kro_prod`, A, B)
}

krao_prod <- function(A, B) {
    .Call(`_tnsrcomp_krao_prod`, A, B)
}

unfold_ten <- function(tens) {
    .Call(`_tnsrcomp_unfold_ten`, tens)
}

fold_ten <- function(A, dim, mode) {
    .Call(`_tnsrcomp_fold_ten`, A, dim, mode)
}

f_norm <- function(tens, approx) {
    .Call(`_tnsrcomp_f_norm`, tens, approx)
}

tens_mat <- function(tens, X, mode) {
    .Call(`_tnsrcomp_tens_mat`, tens, X, mode)
}

core_ten <- function(core_mat) {
    .Call(`_tnsrcomp_core_ten`, core_mat)
}

find_core <- function(tens, mats) {
    .Call(`_tnsrcomp_find_core`, tens, mats)
}

vec_tensor <- function(A, B, C) {
    .Call(`_tnsrcomp_vec_tensor`, A, B, C)
}

als_up <- function(X_list, tens_list, mode, nng) {
    .Call(`_tnsrcomp_als_up`, X_list, tens_list, mode, nng)
}

wy_bls <- function(X_modes, tens_list, mode, tau, beta) {
    .Call(`_tnsrcomp_wy_bls`, X_modes, tens_list, mode, tau, beta)
}

bontf <- function(X, X_n, tnsr_list, rank, iter, tol, nng) {
    .Call(`_tnsrcomp_bontf`, X, X_n, tnsr_list, rank, iter, tol, nng)
}

uo_decomp <- function(X, X_n, tnsr_list, rank, iter, tol, nng) {
    .Call(`_tnsrcomp_uo_decomp`, X, X_n, tnsr_list, rank, iter, tol, nng)
}

ntd <- function(X, X_n, tnsr_list, rank, iter, tol) {
    .Call(`_tnsrcomp_ntd`, X, X_n, tnsr_list, rank, iter, tol)
}

cp_als <- function(tens, modes, rank, iter, thres) {
    .Call(`_tnsrcomp_cp_als`, tens, modes, rank, iter, thres)
}

gramat <- function(layer) {
    .Call(`_tnsrcomp_gramat`, layer)
}

rcpparma_hello_world <- function() {
    .Call(`_tnsrcomp_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_tnsrcomp_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_tnsrcomp_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_tnsrcomp_rcpparma_bothproducts`, x)
}

get_fiber <- function(R, B_out, Cim) {
    .Call(`_tnsrcomp_get_fiber`, R, B_out, Cim)
}

get_fiber_cum <- function(R, B_out, Cim, ai, am) {
    .Call(`_tnsrcomp_get_fiber_cum`, R, B_out, Cim, ai, am)
}

ts_dot_v <- function(X, v) {
    .Call(`_tnsrcomp_ts_dot_v`, X, v)
}

true_Sigma <- function(Sigma_W, Sigma_Z, i, j) {
    .Call(`_tnsrcomp_true_Sigma`, Sigma_W, Sigma_Z, i, j)
}

true_weight <- function(Sigma_W, Sigma_Z, i, j) {
    .Call(`_tnsrcomp_true_weight`, Sigma_W, Sigma_Z, i, j)
}

inv_weight <- function(Sigma) {
    .Call(`_tnsrcomp_inv_weight`, Sigma)
}

weighted_cov_true <- function(X, Sigma_W, Sigma_Z) {
    .Call(`_tnsrcomp_weighted_cov_true`, X, Sigma_W, Sigma_Z)
}

weighted_cov_est <- function(XX, mean_XX_L, est_Sigma_Z) {
    .Call(`_tnsrcomp_weighted_cov_est`, XX, mean_XX_L, est_Sigma_Z)
}

ind2subC <- function(ind, L1, L2) {
    .Call(`_tnsrcomp_ind2subC`, ind, L1, L2)
}

get_tube <- function(X, i, j) {
    .Call(`_tnsrcomp_get_tube`, X, i, j)
}

CimCMat <- function(Mat, L1, L2, i, m) {
    .Call(`_tnsrcomp_CimCMat`, Mat, L1, L2, i, m)
}

CimCX <- function(X, L2, i, m) {
    .Call(`_tnsrcomp_CimCX`, X, L2, i, m)
}

CimCX_cov <- function(X, L2, i, m) {
    .Call(`_tnsrcomp_CimCX_cov`, X, L2, i, m)
}

CimC <- function(X, Y, L2, i, m) {
    .Call(`_tnsrcomp_CimC`, X, Y, L2, i, m)
}

build_D <- function(X, Y, A, B, BtB) {
    .Call(`_tnsrcomp_build_D`, X, Y, A, B, BtB)
}

GjnCX <- function(X, L1, j, n) {
    .Call(`_tnsrcomp_GjnCX`, X, L1, j, n)
}

GjnCMat <- function(Mat, L1, L2, j, n) {
    .Call(`_tnsrcomp_GjnCMat`, Mat, L1, L2, j, n)
}

GjnCX_cov <- function(X, L1, j, n) {
    .Call(`_tnsrcomp_GjnCX_cov`, X, L1, j, n)
}

GjnC <- function(X, Y, L1, j, n) {
    .Call(`_tnsrcomp_GjnC`, X, Y, L1, j, n)
}

build_G <- function(X, Y, A_new, B, AtA) {
    .Call(`_tnsrcomp_build_G`, X, Y, A_new, B, AtA)
}

symmetric_decompC_test <- function(X, Y, R, tol = 1e-4, MAX_ITER = 50L) {
    .Call(`_tnsrcomp_symmetric_decompC_test`, X, Y, R, tol, MAX_ITER)
}

zero_non_zero_summary <- function(A0, B0, A, B) {
    .Call(`_tnsrcomp_zero_non_zero_summary`, A0, B0, A, B)
}

sim_single_block <- function(L, M, rho, alpha) {
    .Call(`_tnsrcomp_sim_single_block`, L, M, rho, alpha)
}

symmetric_decompXC <- function(X, R, L1, L2, tol = 1e-4, MAX_ITER = 50L, type = 1L) {
    .Call(`_tnsrcomp_symmetric_decompXC`, X, R, L1, L2, tol, MAX_ITER, type)
}

