# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kro_prod <- function(A, B) {
    .Call(`_tnsrcomp_kro_prod`, A, B)
}

krao_prod <- function(A, B) {
    .Call(`_tnsrcomp_krao_prod`, A, B)
}

unfold_ten <- function(tens) {
    .Call(`_tnsrcomp_unfold_ten`, tens)
}

fold_ten <- function(A, dim, mode) {
    .Call(`_tnsrcomp_fold_ten`, A, dim, mode)
}

f_norm <- function(tens, approx) {
    .Call(`_tnsrcomp_f_norm`, tens, approx)
}

tens_mat <- function(tens, X, mode) {
    .Call(`_tnsrcomp_tens_mat`, tens, X, mode)
}

core_ten <- function(core_mat) {
    .Call(`_tnsrcomp_core_ten`, core_mat)
}

find_core <- function(tens, mats) {
    .Call(`_tnsrcomp_find_core`, tens, mats)
}

vec_tensor <- function(A, B, C) {
    .Call(`_tnsrcomp_vec_tensor`, A, B, C)
}

als_up <- function(X_list, tens_list, mode, nng) {
    .Call(`_tnsrcomp_als_up`, X_list, tens_list, mode, nng)
}

wy_bls <- function(X_modes, tens_list, mode, tau, beta) {
    .Call(`_tnsrcomp_wy_bls`, X_modes, tens_list, mode, tau, beta)
}

bontf <- function(X, X_n, tnsr_list, rank, iter, tol, nng) {
    .Call(`_tnsrcomp_bontf`, X, X_n, tnsr_list, rank, iter, tol, nng)
}

uo_decomp <- function(X, X_n, tnsr_list, rank, iter, tol, nng) {
    .Call(`_tnsrcomp_uo_decomp`, X, X_n, tnsr_list, rank, iter, tol, nng)
}

ntd <- function(X, X_n, tnsr_list, rank, iter, tol) {
    .Call(`_tnsrcomp_ntd`, X, X_n, tnsr_list, rank, iter, tol)
}

cp_als <- function(tens, modes, rank, iter, thres) {
    .Call(`_tnsrcomp_cp_als`, tens, modes, rank, iter, thres)
}

gramat <- function(layer) {
    .Call(`_tnsrcomp_gramat`, layer)
}

